public enum GameLocation {
    START, DECISION_START, SEARCH_WRECKAGE, WRECKAGE_DANGER, SEARCH_WRECKAGE_BAG, AFTER_WRECKAGE_DECISION,
    RIVER_PATH, DECISION_RIVER, RIVER_PATH_CONTINUED, WATERFALL_CAVE, INSIDE_CAVE, BOAR_ENCOUNTER,
    JUNGLE_PATH, FIND_SPEAR, DECISION_JUNGLE, GIANT_TREE, SPIDER_ENCOUNTER, AFTER_SPIDER_FIGHT,
    QUICKSAND_SWAMP, FIND_KIT_2, FIND_KIT_3,
    ENEMY_ENCOUNTER, FIGHT, PLAYER_ATTACK, PLAYER_HEAL, ENEMY_ATTACK,
    WIN_FIGHT, FLEE_RESULT, ENEMY_ATTACK_DISPLAY,
    DECISION_RIVER_DAMAGE, FIND_PENDANT, AFTER_PENDANT,
    DECISION_FINAL, BRIDGE_CROSS_SUCCESS, ENDING_ESCAPE, ENDING_RESCUE, ENDING_LOST,
    LOSE, THANK_YOU,
    WEAPON_CHOICE,
    MURKY_DELTA, DELTA_ISLAND, FIND_MAIN_CHANNEL, GIANT_CRAB_ENCOUNTER,
    ANCIENT_RUINS, RUINS_CRYPT, RUINS_BUILDING, STALKER_ENCOUNTER, AFTER_STALKER_FIGHT
}